[project]
name = "My-Chef"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yassincode20", email = "xistyxistyde@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
my-chef = "my_chef:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
